<a href="https://colab.research.google.com/github/TwoGunTitan/Vision-without-glasses/blob/main/densenet121.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from tensorflow import keras
import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt
import cv2
import pandas as pd

In [ ]:
!pip install tensorflow-gpu

In [ ]:
# %tensorflow_version 2.x
# import tensorflow as tf
# device_name = tf.test.gpu_device_name()
# if device_name != '/device:GPU:0':
#   raise SystemError('GPU device not found')
# print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
from keras.preprocessing import image
def load_images(filename):
  labels =[]
  np.random.shuffle(filename)
  X = []
  i=0
  for name,label in filename:
    img = image.load_img(name,target_size=(244,244))
    x = tf.keras.preprocessing.image.img_to_array(img)
    x = keras.applications.densenet.preprocess_input(x)
    X.append(x)
    labels.append(label)
    print(i)
    i=i+1
  return np.array(X), np.array(labels)

In [ ]:
base_model = tf.keras.applications.densenet.DenseNet121(include_top=False, weights='imagenet')

29097984/29084464 [==============================] - 0s 0us/step


In [ ]:
base_model.trainable=False
inputs = keras.Input(shape=(244,244,3))
x = inputs
x = base_model(x, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
outputs = keras.activations.sigmoid(keras.layers.Dense(1)(x))
model = keras.Model(inputs, outputs)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 244, 244, 3)]     0         
                                                                 
 densenet121 (Functional)    (None, None, None, 1024)  7037504   
                                                                 
 global_average_pooling2d (G  (None, 1024)             0         
 lobalAveragePooling2D)                                          
                                                                 
 dense (Dense)               (None, 1)                 1025      
                                                                 
 tf.math.sigmoid (TFOpLambda  (None, 1)                0         
 )                                                               
                                                                 
Total params: 7,038,529
Trainable params: 1,025
Non-trainable

In [ ]:
model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=[keras.metrics.BinaryAccuracy()],
)
a = np.array(train_dataset)
epochs = 20
x,y = load_images(a)

KeyboardInterrupt: ignored

In [ ]:
model.load_weights('/content/drive/MyDrive/dogs_vs_cats_dataset/densenet_normal')

In [ ]:
path = '/content/drive/MyDrive/dogs_vs_cats_dataset/test_data/normal_dataset/'
classes = ['cat.','dog.']
test_dataset = []
for i in range(100):
  for label in range(2):
    test_dataset.append([path+classes[label]+str(i)+'.jpg',label])
np.array(test_dataset)
x_blur, y_blur = load_images(test_dataset)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199


In [ ]:
y_predicted = model.predict(x_blur)
y_predicted.round()
acc = keras.metrics.BinaryAccuracy()
acc.update_state(y_blur, y_predicted[:, 0]).numpy()
acc.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.985>

In [ ]:
print(y_predicted[0:10].round())
print(y_blur[0:10])

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]]
[1 1 0 1 1 0 1 0 0 1]
